name: square_reader_sdk
description: An open source Flutter plugin for calling Square’s native Reader SDK implementations to take in-person payments on iOS and Android.
version: 2.3.0
homepage: https://github.com/square/reader-sdk-flutter-plugin

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^7.0.0
  built_collection: ^4.0.0

dev_dependencies:
  build: ^1.1.0
  build_runner: ^1.2.3
  source_gen:  ^0.9.4+1
  built_value_generator: ^7.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.squareup.sdk.reader.flutter
        pluginClass: SquareReaderSdkFlutterPlugin
      ios:
        pluginClass: SquareReaderSdkFlutterPlugin
