name: build

on:
  push:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter pub get
      #IOS
      - run: |
          cd example
          cd ios
          ruby <(curl https://connect.squareup.com/readersdk-installer) install
          --app-id ${{ secrets.USERNAME }}
          --repo-password ${{ secrets.PASSWORD }} >
          cd ..
          flutter pub get
          flutter build ios --no-codesign
      #Android
      - run: |
          cd example
          flutter pub get
          openssl aes-256-cbc -K ${{secrets.ENCRYPTED_KEY}} -iv ${{secrets.ENCRYPTED_IV}}
            - in android/gradle.properties.enc -out android/gradle.properties -d
          flutter build apk
      - name: Send mail
          if: always()
          uses: dawidd6/action-send-mail@v2
          with:
            # mail server settings
            server_address: smtp.gmail.com
            server_port: 465
            # user credentials
            username: ${{ secrets.EMAIL_USERNAME }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            # email subject
            subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
            # email body as text
            body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
            # comma-separated string, send email to
            to: dexteam+alerts@squareup.com
            # from email name
            from: ${{ github.repository }}